# Generated by Django 3.0.5 on 2021-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdetails',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
