# Generated by Django 3.0.5 on 2021-05-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210515_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
